name: proxy_provider
packages:
  - packages/**
repository: https://github.com/blaugold/proxy_provider

ide:
  intellij: false

command:
  version:
    branch: main
    linkToCommits: true
    workspaceChangelog: true

scripts:
  flutter:pub:get: melos exec -c 1 --flutter -- flutter pub get
  formatting:apply: dart format .
  formatting:check: dart format . --set-exit-if-changed
  analyze: melos exec -c 1 -- dart analyze --fatal-infos
