name: proxy_provider_flutter_example
description: Demonstrates how to use the proxy_provider_flutter plugin.
publish_to: 'none'

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  proxy_provider:
    path: ../../proxy_provider
  proxy_provider_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
