name: proxy_provider_flutter
description:
  Flutter plugin for resolving network proxy configuration from system services
  or custom providers.
version: 0.1.0
homepage: https://github.com/blaugold/proxy_provider/tree/main/packages/proxy_provider_flutter
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  proxy_provider:
    path: ../proxy_provider

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: net.terwesten.gabriel.proxy_provider_flutter
        pluginClass: ProxyProviderFlutterPlugin
        dartPluginClass: AndroidProxyProviderFlutterPlugin
      ios:
        pluginClass: ProxyProviderFlutterPlugin
        dartPluginClass: NoopProxyProviderFlutterPlugin
      linux:
        pluginClass: ProxyProviderFlutterPlugin
        dartPluginClass: NoopProxyProviderFlutterPlugin
      macos:
        pluginClass: ProxyProviderFlutterPlugin
        dartPluginClass: NoopProxyProviderFlutterPlugin
