name: proxy_provider
description:
  Package for resolving network proxy configuration from system services or
  custom providers.
version: 0.1.0
homepage: https://github.com/blaugold/proxy_provider/tree/main/packages/proxy_provider

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  ffi: ^1.1.2
  meta: ^1.7.0

dev_dependencies:
  test: ^1.16.0
